export const category = [
  {type: 'any category', id: ''},
  {type: 'general knowledge', id: '9'},
  {type: 'entertainment: books', id: '10'},
  {type: 'entertainment: film', id: '11'},
  {type: 'entertainment: music', id: '12'},
  {type: 'entertainment: musical & theatres', id: '13'},
  {type: 'entertainment: television', id: '14'},
  {type: 'entertainment: video games', id: '15'},
  {type: 'entertainment: board games', id: '16'},
  {type: 'science & nature', id: '17'},
  {type: 'science: computers', id: '18'},
  {type: 'science: mathematics', id: '19'},
  {type: 'mythology', id: '20'},
  {type: 'sports', id: '21'},
  {type: 'geopgraphy', id: '22'},
  {type: 'history', id: '23'},
  {type: 'politics', id: '24'},
  {type: 'art', id: '25'},
  {type: 'celebrities', id: '26'},
  {type: 'animals', id: '27'},
  {type: 'vehicles', id: '28'},
  {type: 'entertainment: comics', id: '29'},
  {type: 'science: gadgets', id: '30'},
  {type: 'entertainment: japanese anime & manga', id: '31'},
  {type: 'entertainment: cartoon & animations', id: '32'},
]
